# Generated by Django 3.2.13 on 2022-06-23 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_builder_api', '0002_rename_menu_modifiers_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modifiers',
            old_name='Items',
            new_name='items',
        ),
    ]
