# Generated by Django 3.2.13 on 2022-06-24 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_builder_api', '0003_rename_items_modifiers_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menu',
            },
        ),
        migrations.RenameField(
            model_name='items',
            old_name='title',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='modifiers',
            old_name='title',
            new_name='description',
        ),
        migrations.AddField(
            model_name='items',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='items',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.RemoveField(
            model_name='modifiers',
            name='items',
        ),
        migrations.AddField(
            model_name='modifiers',
            name='items',
            field=models.ManyToManyField(related_name='items', to='menu_builder_api.Items'),
        ),
        migrations.AlterField(
            model_name='items',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='menu_builder_api.section'),
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
