# Generated by Django 3.2.13 on 2022-06-24 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_builder_api', '0004_auto_20220624_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu_builder_api.section'),
        ),
        migrations.AlterField(
            model_name='modifiers',
            name='items',
            field=models.ManyToManyField(related_name='modifiers', to='menu_builder_api.Items'),
        ),
    ]
