# Generated by Django 3.2.13 on 2022-06-24 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_builder_api', '0005_auto_20220624_1008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='menu',
            new_name='section',
        ),
    ]
