# Generated by Django 3.2.13 on 2022-06-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_builder_api', '0008_rename_modifiers_description_modifiers_modifiers_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modifiers',
            name='items',
            field=models.ManyToManyField(related_name='modifiers', to='menu_builder_api.Items'),
        ),
    ]
